'use strict';
/** Local-only durable-memory prototype. No runtime integration or legacy import. */
const fs = require('fs'); const path = require('path'); const crypto = require('crypto');
const TYPES=new Set(['project','repository','component','file','service','environment','person','role','agent','team','task','goal','decision','procedure','external_system','document','concept']);
const CLAIM_TYPES=new Set(['fact','preference','decision','constraint','obligation','assessment']);
const EDGES=new Set(['about','predicate','depends_on','implements','related_to','derived_from','supports','contradicts','supersedes','scoped_to']);
const PREDICATES=new Set(['has_status','has_version','located_at','uses_backend','requires','owned_by','configured_by','implements','governed_by','depends_on','does_not','has_capability','has_risk']);
const SOURCE=new Set(['user_statement','repository','tool_result','spec_keeper','agent_bus','external_document','manual']);
const SECRET=/(?:authorization|bearer\s+|password|secret|token|api[_-]?key|private key|-----begin|eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.)/i;
const iso=s=>typeof s==='string'&&!Number.isNaN(Date.parse(s));
const canon=v=>JSON.stringify(canonical(v),null,2)+'\n';
const digest=v=>crypto.createHash('sha256').update(typeof v==='string'?v:canon(v)).digest('hex');
const fail=m=>{throw new Error(m)};
function safeText(s,field='text',limit=1000){if(typeof s!=='string'||!s.trim()||s.length>limit||/[\x00-\x1f\x7f]/.test(s)||SECRET.test(s))fail(`unsafe ${field}`); return s.normalize('NFC');}
function safeLocator(s){safeText(s,'locator',512); if(/(^\/|\.\.|[?#]|:\/\/[^/]*@)/.test(s))fail('unsafe locator'); return s;}
function canonical(value){ if(Array.isArray(value))return value.map(canonical); if(value&&typeof value==='object'){const out={};for(const k of Object.keys(value).sort())out[k]=canonical(value[k]);return out;} if(typeof value==='number'&&(!Number.isFinite(value)||Object.is(value,-0)))fail('invalid number'); return value; }
function stringify(value,pretty=true){return JSON.stringify(canonical(value),null,pretty?2:0)+(pretty?'\n':'');}
function graph(){const now=new Date().toISOString();return {schema_version:'1.0',graph_id:`g-${crypto.randomUUID()}`,created_at:now,updated_at:now,nodes:[],edges:[],provenance:[]};}
function validateGraph(g){
 if(!g||g.schema_version!=='1.0'||typeof g.graph_id!=='string'||!iso(g.created_at)||!iso(g.updated_at))fail('invalid graph envelope');
 for(const k of ['nodes','edges','provenance'])if(!Array.isArray(g[k]))fail(`missing ${k}`);
 const ids=new Set(); for(const n of g.nodes){if(ids.has(n.id)||typeof n.id!=='string')fail('duplicate/invalid node');ids.add(n.id);safeText(n.label,'label',160);if(n.summary!==undefined)safeText(n.summary,'summary');if(!['active','superseded','retracted','archived'].includes(n.status)||!iso(n.created_at)||!iso(n.updated_at)||!Array.isArray(n.provenance_ids))fail('invalid node fields');if(n.kind==='entity'?!TYPES.has(n.type):n.kind==='claim'?!CLAIM_TYPES.has(n.type):true)fail('invalid node type');if(n.kind==='claim'&&(!(n.confidence>=0&&n.confidence<=1)||!['observed','reported','inferred','imported'].includes(n.epistemic_basis)||!iso(n.asserted_at)))fail('invalid claim');}
 const pids=new Set();for(const p of g.provenance){if(pids.has(p.id)||!SOURCE.has(p.source_kind)||!iso(p.observed_at)||!iso(p.recorded_at))fail('invalid provenance');pids.add(p.id);safeLocator(p.locator);if(p.excerpt_or_digest)safeText(p.excerpt_or_digest,'digest',512)}
 for(const n of g.nodes)for(const p of n.provenance_ids)if(!pids.has(p))fail('unknown provenance');
 const es=new Set();const count={};for(const e of g.edges){if(es.has(e.id)||!EDGES.has(e.type)||!ids.has(e.from_id)||!['active','superseded','retracted','archived'].includes(e.status))fail('invalid edge');es.add(e.id);if(e.type==='predicate'){if(!PREDICATES.has(e.attributes?.name)||((e.to_id===undefined)===(e.attributes?.value===undefined)))fail('invalid predicate')}else if(!ids.has(e.to_id))fail('unknown edge target');if(e.type==='about'||e.type==='predicate')count[`${e.from_id}:${e.type}`]=(count[`${e.from_id}:${e.type}`]||0)+1;}
 for(const n of g.nodes)if(n.kind==='claim'&&n.status==='active'&&(count[`${n.id}:about`]!==1||count[`${n.id}:predicate`]!==1||!n.provenance_ids.length))fail('invalid active claim assertion');return true;
}
function apply(g,op){const x=structuredClone(g); const mutate=o=>{if(o.kind==='add_node')x.nodes.push(o.node);else if(o.kind==='add_provenance')x.provenance.push(o.provenance);else if(o.kind==='add_edge')x.edges.push(o.edge);else if(o.kind==='update_node'){const n=x.nodes.find(n=>n.id===o.id);if(!n)fail('unknown node');Object.assign(n,o.patch,{updated_at:o.at});}else fail('unknown operation');}; if(op.kind==='batch'){if(!Array.isArray(op.operations)||op.operations.length<1||op.operations.length>20)fail('invalid batch');for(const nested of op.operations)mutate(nested);}else mutate(op);x.updated_at=op.at;validateGraph(x);return x;}
function init(root){fs.mkdirSync(root,{recursive:true,mode:0o700});for(const d of ['journal','audit','quarantine'])fs.mkdirSync(path.join(root,d),{mode:0o700});const g=graph(), snap=stringify(g), manifest={format_version:'1.0',graph_id:g.graph_id,snapshot:{path:'graph.snapshot.json',sequence:0,sha256:digest(snap)},journal:{first_sequence:0,last_sequence:0,segments:[]},updated_at:g.updated_at}; atomic(root,'graph.snapshot.json',snap);atomic(root,'manifest.json',stringify(manifest));return g;}
function atomic(root,name,data){const target=path.join(root,name),tmp=`${target}.tmp-${crypto.randomUUID()}`;fs.writeFileSync(tmp,data,{mode:0o600});fs.renameSync(tmp,target);}
function load(root){const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));const snap=fs.readFileSync(path.join(root,m.snapshot.path),'utf8');if(digest(snap)!==m.snapshot.sha256)fail('snapshot digest mismatch');let g=JSON.parse(snap);let expected=m.snapshot.sequence+1;for(const s of m.journal.segments){const text=fs.readFileSync(path.join(root,s.path),'utf8');if(digest(text)!==s.sha256)fail('journal digest mismatch');for(const line of text.trimEnd().split('\n')){const item=JSON.parse(line);if(item.sequence!==expected++)fail('journal sequence gap');g=apply(g,item.operation)}}if(expected-1!==m.journal.last_sequence)fail('journal boundary mismatch');validateGraph(g);return {g,m};}
function commit(root, operations){let {g,m}=load(root);const seq=m.journal.last_sequence;const lines=[];for(let i=0;i<operations.length;i++){g=apply(g,operations[i]);lines.push(JSON.stringify(canonical({at:operations[i].at,graph_id:g.graph_id,operation:operations[i],sequence:seq+i+1}))+'\n')}const first=seq+1, rel=`journal/${String(first).padStart(20,'0')}.jsonl`, text=lines.join('');atomic(root,rel,text);m.journal={first_sequence:first,last_sequence:seq+operations.length,segments:[...m.journal.segments,{first_sequence:first,last_sequence:seq+operations.length,path:rel,sha256:digest(text)}]};m.updated_at=g.updated_at;atomic(root,'manifest.json',stringify(m));return g;}
function retrieve(g,q){validateGraph(g);const tokens=new Set((q.task_text||'').toLowerCase().match(/[\p{L}\p{N}_-]+/gu)||[]), asOf=q.as_of||new Date().toISOString(), scopes=new Set(q.scope_entity_ids||[]), intent=q.intent||'lookup';let cards=[];for(const c of g.nodes.filter(n=>n.kind==='claim'&&n.status==='active')){if(c.valid_from&&c.valid_from>asOf||c.valid_until&&c.valid_until<=asOf)continue;const about=g.edges.find(e=>e.from_id===c.id&&e.type==='about'&&e.status==='active');const pred=g.edges.find(e=>e.from_id===c.id&&e.type==='predicate'&&e.status==='active');const scope=g.edges.filter(e=>e.from_id===c.id&&e.type==='scoped_to'&&e.status==='active').map(e=>e.to_id);if(scope.length&&!scope.some(x=>scopes.has(x)))continue;const subject=g.nodes.find(n=>n.id===about.to_id);const assertion=`${subject.label} ${pred.attributes.name} ${pred.to_id||String(pred.attributes.value)}`;const match=[...tokens].filter(t=>assertion.toLowerCase().includes(t)).length;const score=.35*Math.min(1,match/Math.max(1,tokens.size))+.2*c.confidence+.15+.15+.1*(scope.length?1:0);cards.push({id:c.id,label:c.label,assertion,confidence:c.confidence,score:+score.toFixed(3),reasons:['active','provenanced',match?'task-token-match':'weak-match'],conflict_with:[]});}for(const card of cards){for(const e of g.edges.filter(e=>e.type==='contradicts'&&(e.from_id===card.id||e.to_id===card.id)&&e.status==='active'))card.conflict_with.push(e.from_id===card.id?e.to_id:e.from_id)}cards.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));const max=q.max_claims||8, selected=cards.slice(0,max);return {query_id:`q-${crypto.randomUUID()}`,graph_id:g.graph_id,cards:selected,omissions:cards.length>max?[`${cards.length-max} claims omitted by budget`]:[],warnings:selected.some(c=>c.conflict_with.length)?['unresolved conflict included']:[]};}
function consolidate(g){validateGraph(g);const groups=new Map();for(const c of g.nodes.filter(n=>n.kind==='claim'&&n.status==='active')){const a=g.edges.find(e=>e.from_id===c.id&&e.type==='about'),p=g.edges.find(e=>e.from_id===c.id&&e.type==='predicate');const k=`${a.to_id}|${p.attributes.name}|${p.to_id||JSON.stringify(p.attributes.value)}`;(groups.get(k)||groups.set(k,[]).get(k)).push(c)}const ops=[];for(const group of groups.values())if(group.length>1){group.sort((a,b)=>b.confidence-a.confidence||a.id.localeCompare(b.id));const [winner,...losers]=group;for(const loser of losers){const at=new Date().toISOString();ops.push({kind:'update_node',id:loser.id,patch:{status:'superseded'},at});ops.push({kind:'add_edge',at,edge:{id:`e-${crypto.randomUUID()}`,type:'supersedes',from_id:winner.id,to_id:loser.id,status:'active',created_at:at,updated_at:at,provenance_ids:[]}})}}return ops;}
module.exports={graph,validateGraph,init,load,commit,retrieve,consolidate,safeText};
