import assert from "node:assert/strict";
import { runPlanningLoop, planningCallAllowed } from "../llm/planning-loop.js";
import type { CompatibleResponse, CompatibleCreateRequest } from "../llm/multi-turn-runtime.js";
const call = (name: string, args: object = {}) => ({ type: "function_call" as const, call_id: name, name, arguments: JSON.stringify(args) });
const reply = (id: string, output: CompatibleResponse["output"]): CompatibleResponse => ({ id, output });
const final = (text: string) => ({ type: "message" as const, status: "completed" as const, content: [{ type: "output_text" as const, text }] });
const plan = JSON.stringify({ steps: [{ step_number: 1, tldr: "Implement the observed fix" }] });
async function main() {
    const requests: CompatibleCreateRequest[] = [];
    const dispatched: string[] = [];
    const responses = [reply("1", [call("Read", { path: "README.md" })]), reply("2", [call("Http", { url: "https://example.com" })]), reply("3", [final("not json")]), reply("4", [final(plan)])];
    const result = await runPlanningLoop({ prompt: "instructions", tools: [], create: async (request) => { requests.push(request); return responses.shift()!; }, onResponse: () => {}, dispatch: async (c) => { dispatched.push(c.name); return { type: "function_call_output", call_id: c.call_id, output: JSON.stringify({ content: "research evidence" }) }; } });
    assert.equal(result.result.kind, "plan");
    assert.deepEqual(dispatched, ["Read", "Http"]);
    assert.equal(requests[1].previous_response_id, "1");
    assert.equal(requests[2].previous_response_id, "2");
    assert.match(String(requests[3].input), /research evidence/);
    assert.match(String(requests[3].input), /not json/);
    assert.equal(planningCallAllowed(call("Write")), false);
    assert.equal(planningCallAllowed(call("Git", { action: "commit" })), false);
    assert.equal(planningCallAllowed(call("Git", { mode: "status" })), true);
    assert.equal(planningCallAllowed(call("Http", { method: "POST" })), false);
    assert.equal(planningCallAllowed(call("ExecuteCommand")), false);
    let executed = 0;
    const base = { prompt: "x", tools: [], onResponse: () => {}, dispatch: async (c: ReturnType<typeof call>) => { executed++; return { type: "function_call_output" as const, call_id: c.call_id, output: "{}" }; } };
    await assert.rejects(runPlanningLoop({ ...base, maxToolRounds: 1, create: async () => reply("loop", [call("Read")]) }), /budget exhausted/);
    assert.equal(executed, 1);
    const abort = new AbortController(); abort.abort();
    await assert.rejects(runPlanningLoop({ ...base, signal: abort.signal, create: async () => { throw new Error("must not generate"); } }), /abort/i);
    const refused = [reply("deny", [call("Write")]), reply("done", [final(plan)])];
    executed = 0;
    await runPlanningLoop({ ...base, create: async (request) => { if (request.previous_response_id) assert.match(JSON.stringify(request.input), /research only/); return refused.shift()!; } });
    assert.equal(executed, 0);
    const aborted = await runPlanningLoop({ ...base, create: async () => reply("abort", [final('{"abort":true,"reason":"Missing evidence"}')]) });
    assert.equal(aborted.result.kind, "abort");
    console.log("Planning loop research, continuation, repair, restrictions, budgets, and abort tests passed.");
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
