/**
 * In-memory graph store backing `GraphMemoryModule` (`memory/graph-memory.ts`).
 *
 * This file defines the logical graph schema used by the graph memory module —
 * `GraphNode`, `GraphEdge`, the `GraphStore` storage interface, and a concrete
 * in-memory implementation (`InMemoryGraphStore`). The schema mirrors the
 * logical data model in `GRAPH_DATA_MODEL.md` and the physical layout target in
 * `MEMORY_FILE_LAYOUT.md` so the shape can later be serialized to a persistent
 * backend without changing `GraphMemoryModule` itself.
 *
 * The store is deliberately narrow and transport-agnostic: it knows nothing
 * about LLM modules, sessions, or summarization. `GraphMemoryModule` builds
 * nodes/edges from plan steps and stores/reads them through this interface, so
 * a persistent backend (file, SQLite, remote) can replace the in-memory store
 * later by implementing `GraphStore` and injecting it via the module's factory
 * options.
 */

/** Lifecycle status of a graph node, drawn from the logical data model. */
export type GraphNodeStatus = "active" | "superseded" | "retracted" | "archived";

/** Controlled node kinds: durable referents vs. atomic assertions. */
export type GraphNodeKind = "entity" | "claim";

/** Controlled entity/claim types used by the graph memory module. */
export type GraphNodeType =
  // entity
  | "agent"
  | "plan"
  | "task"
  | "project"
  | "repository"
  | "component"
  | "concept"
  // claim
  | "fact"
  | "decision"
  | "assessment"
  | "obligation"
  | "preference"
  | "constraint";

/** Typed, directed edge types from the logical data model. */
export type GraphEdgeType =
  | "depends_on"
  | "derived_from"
  | "about"
  | "predicate"
  | "supports"
  | "supersedes"
  | "related_to"
  | "scoped_to";

/**
 * Small typed map used for node/edge attributes (namespaced keys). Values are
 * scalars or arrays of scalars so structured-but-bounded payloads (e.g. a list
 * of action names) can be stored without a lossy stringification.
 */
export type GraphAttributeValue = boolean | number | string | null | readonly GraphAttributeValue[];
export type GraphAttributes = Readonly<Record<string, GraphAttributeValue>>;

/**
 * A single node in the graph memory model.
 *
 * `id` is an opaque immutable identifier generated by the store/module. A node
 * is either a durable `entity` (plan, project, ...) or an atomic `claim`
 * (fact, decision, ...) carrying an optional bounded set of attributes.
 */
export interface GraphNode {
  /** Opaque immutable identifier. */
  readonly id: string;
  /** `entity` for durable referents, `claim` for atomic assertions. */
  readonly kind: GraphNodeKind;
  /** Controlled type (agent, plan, task, fact, assessment, ...). */
  readonly type: GraphNodeType;
  /** Short display label. */
  readonly label: string;
  /** The run/session this node belongs to. */
  readonly sessionId: string;
  /** Lifecycle status. */
  readonly status: GraphNodeStatus;
  /** RFC 3339 timestamp when the node was created. */
  readonly createdAt: string;
  /** RFC 3339 timestamp when the node was last updated. */
  readonly updatedAt: string;
  /** Optional bounded scalar attribute map. */
  readonly attributes?: GraphAttributes;
}

/**
 * A single directed edge linking two nodes within the same graph.
 *
 * Both endpoints must exist in the store; the module only creates edges for
 * nodes it has already upserted. `value` carries an optional typed scalar for a
 * `predicate` edge; `attributes` is an optional bounded scalar map.
 */
export interface GraphEdge {
  /** Opaque immutable identifier. */
  readonly id: string;
  /** Typed edge type (depends_on, derived_from, about, ...). */
  readonly type: GraphEdgeType;
  /** Source node id. */
  readonly fromId: string;
  /** Target node id. */
  readonly toId: string;
  /** Lifecycle status. */
  readonly status: GraphNodeStatus;
  /** Optional typed scalar for a `predicate` edge. */
  readonly value?: GraphAttributeValue;
  /** Optional bounded scalar attribute map. */
  readonly attributes?: GraphAttributes;
}

/**
 * The storage boundary used by `GraphMemoryModule`.
 *
 * This is the only interface `GraphMemoryModule` depends on for storage, so a
 * persistent backend may be swapped in later without modifying the module.
 */
export interface GraphStore {
  /** Insert or update a node (by `id`). */
  upsertNode(node: GraphNode): void;
  /** Insert or update an edge (by `id`). */
  upsertEdge(edge: GraphEdge): void;
  /** Look up a single node by id, if present. */
  getNode(id: string): GraphNode | undefined;
  /** All step (claim) nodes for a session in OLDEST-first order. */
  stepsForSession(sessionId: string): GraphNode[];
  /** The `n` most recent step nodes for a session, NEWEST-first. */
  recentChain(sessionId: string, n: number): GraphNode[];
  /** The plan entity node for a session, if present. */
  planForSession(sessionId: string): GraphNode | undefined;
  /** All edges with `fromId` equal to the given node id. */
  edgesFrom(nodeId: string): GraphEdge[];
}

/**
 * Concrete in-memory graph store.
 *
 * Backed by adjacency maps — `nodes: Map<id, GraphNode>`,
 * `edgesByFrom: Map<id, GraphEdge[]>`, and `sessionSteps: Map<sessionId,
 * string[]>` — so the natural query shapes (steps for a session, recent chain,
 * outgoing edges) are O(1) or O(n) over the relevant slice. This is the
 * default store used when `GraphMemoryModule` is constructed without an
 * injected store.
 */
export class InMemoryGraphStore implements GraphStore {
  private readonly nodes = new Map<string, GraphNode>();
  private readonly edgesByFrom = new Map<string, GraphEdge[]>();
  private readonly sessionSteps = new Map<string, string[]>();
  private readonly sessionPlan = new Map<string, string>();

  upsertNode(node: GraphNode): void {
    this.nodes.set(node.id, node);
    if (node.kind === "claim") {
      let steps = this.sessionSteps.get(node.sessionId);
      if (!steps) {
        steps = [];
        this.sessionSteps.set(node.sessionId, steps);
      }
      if (!steps.includes(node.id)) steps.push(node.id);
    } else if (node.kind === "entity" && node.type === "plan") {
      this.sessionPlan.set(node.sessionId, node.id);
    }
  }

  upsertEdge(edge: GraphEdge): void {
    const edges = this.edgesByFrom.get(edge.fromId) ?? [];
    const index = edges.findIndex((e) => e.id === edge.id);
    if (index >= 0) {
      edges[index] = edge;
    } else {
      edges.push(edge);
    }
    this.edgesByFrom.set(edge.fromId, edges);
  }

  getNode(id: string): GraphNode | undefined {
    return this.nodes.get(id);
  }

  stepsForSession(sessionId: string): GraphNode[] {
    const ids = this.sessionSteps.get(sessionId) ?? [];
    return ids.map((id) => this.nodes.get(id)).filter((n): n is GraphNode => n !== undefined);
  }

  recentChain(sessionId: string, n: number): GraphNode[] {
    const steps = this.stepsForSession(sessionId);
    return steps.slice(-n).reverse();
  }

  planForSession(sessionId: string): GraphNode | undefined {
    const id = this.sessionPlan.get(sessionId);
    return id === undefined ? undefined : this.nodes.get(id);
  }

  edgesFrom(nodeId: string): GraphEdge[] {
    return this.edgesByFrom.get(nodeId) ?? [];
  }
}
